# Generated by Django 4.1.5 on 2023-01-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='descricao',
            field=models.CharField(default=1, help_text='Nome do jogo', max_length=2500),
            preserve_default=False,
        ),
    ]
