# Generated by Django 4.1.5 on 2023-01-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0002_personagem_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='descricao',
            field=models.CharField(help_text='Descrição do personagem', max_length=2500),
        ),
    ]
