# Generated by Django 4.1.5 on 2023-01-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_jogo_ano_lancamento_jogo_estilo_jogo_qtd_vendas'),
        ('personagens', '0003_alter_personagem_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='jogo',
            field=models.ManyToManyField(to='jogos.jogo'),
        ),
    ]
