# Generated by Django 4.1.5 on 2023-01-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0004_personagem_jogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='jogo',
            new_name='jogos',
        ),
    ]
