# Generated by Django 4.1.5 on 2023-01-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0005_rename_jogo_personagem_jogos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='jogos',
            new_name='jogos_atrelados',
        ),
    ]
