# Generated by Django 4.1.5 on 2023-01-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0006_rename_jogos_personagem_jogos_atrelados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='descricao',
            field=models.EmailField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
