# Generated by Django 4.1.5 on 2023-01-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0007_alter_personagem_descricao_alter_personagem_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='descricao',
            field=models.CharField(max_length=2500),
        ),
    ]
