# Generated by Django 4.1.5 on 2023-01-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_jogo_ano_lancamento_jogo_estilo_jogo_qtd_vendas'),
        ('fases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='jogo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jogos.jogo'),
            preserve_default=False,
        ),
    ]
