# Generated by Django 4.1.5 on 2023-01-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='ano_lancamento',
            field=models.CharField(default=1, help_text='Ano de lançamento', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogo',
            name='estilo',
            field=models.CharField(default=1, help_text='Estilo de jogo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogo',
            name='qtd_vendas',
            field=models.CharField(default=1, help_text='Quantidade de vendas', max_length=100),
            preserve_default=False,
        ),
    ]
