# Generated by Django 4.1.5 on 2023-01-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0003_remove_jogo_ano_lancamento_remove_jogo_qtd_vendas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
