# Generated by Django 4.1.5 on 2023-01-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0004_jogo_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='imagem',
            field=models.ImageField(default=1, height_field=50, upload_to='media', width_field=50),
            preserve_default=False,
        ),
    ]
